name: Who_is_DC music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#414141'
    - '#d6d6d6'
    - '#828282'
  brandStrength: 1
  lightness: 0.02854612
  saturation: 0.5
  rhythmicContrast: 0.8447987
purpose: []
